### ISSUE TITLE
Question: Stopping the node right after flips creation.

### ISSUE THREAD

**Issue by Gutalean** [idena-network/idena-go#312]
If you stop your node right after flips are created and submitted via a Tx, then wait for example several days and run new node with the same nodekey on another PC will your flips ever be available to the network? How flips become distributed throughout the network? Will they be available if you delete your IPFS directory?

**Comment by ridenaio** [comment]
Hi, thank you for reaching out to us.

Flips are distributed over the network separately from transactions but at the same time. Each flip is saved in local IPFS storage of each node during the current epoch. So, if you have submitted your flips, you can turn your node off or delete your IPFS directory. 
Currently, the idena-desktop application does not have support to show your flips if you run it with the same nodekey on a different machine. However, it will not affect the whole validation process, because flips are already distributed all over the network.
