### ISSUE TITLE
Enormous fee for DeleteFlipTx

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-go#427]
After HF, deleting a submitted flip takes exaggerated amount of DNA as a fee.

From 0.0000000000614635 DNA before to 26.793374019211176 DNA after.

![image](https://user-images.githubusercontent.com/52136297/82026139-9c4e7300-9692-11ea-85f1-7f03121e469a.png)

![image](https://user-images.githubusercontent.com/52136297/82026056-775a0000-9692-11ea-865f-8c1ef1a346fe.png)

**Comment by rioda-org** [comment]
https://scan.idena.io/transaction/0x8bd964e01e5543ca047f030ece21591286948a6f2831802ee7000c499e365bda

**Comment by midenaio** [comment]
@rioda-org Could you give an example of such type of transactions with enormous fee

**Comment by rioda-org** [comment]
> @rioda-org Could you give an example of such type of transactions with enormous fee

Sorry, was not able to get evidence. Heard someone say that but unable to confirm.

**Comment by KruciferX** [comment]
> @rioda-org Could you give an example of such type of transactions with enormous fee

I don't understand this question.

There's a link to the explorer posted by rioda, the same txn that I posted screenshot for.

Also, DeleteFlipTx fee used to be like any other fee, but after announced HF it will be 5 DNA which is still enormous for a single txn fee. Is this on purpose?

**Comment by busimus** [comment]
> Also, DeleteFlipTx fee used to be like any other fee

Ever since this transaction type got introduced, there was a special case in fee calculations for DeleteFlipTx. It has always been a lot larger than regular fees (because its size is [calculated](https://github.com/idena-network/idena-go/blob/master/blockchain/fee/fee_calc.go#L73:L75) as if the size of transaction is the maximum size of a flip, [640KB](https://github.com/idena-network/idena-go/blob/8fa06634694d85c1fcac6e24d3b498a6f6cb59e4/common/network.go#L17)), but regular fees were practically zero.
After HF regular fees became Real, so multiplying them by any amount is very noticeable.

It's probably on purpose, to prevent spamming the network with large flip payloads. Currently 5 DNA is not _that_ bad, especially since it's a voluntary transaction for your convenience. But 5 DNA will be worth 5 lambos in 2025 so it might need adjustment in the future.
