### ISSUE TITLE
MemberD - Validation problem

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#528]
Hi, here are [logs.zip](https://github.com/idena-network/idena-go/files/5080382/logs.zip) from one member.
https://scan.idena.io/identity/0x3c35dc7af31d5e545b4987da056893c784c673e3

He had a problem during validation, his long session got buggy and he's human identity was killed.
He ran node on 1GB of ram vultr instance.
One note though, he said he submitted flip 6 min before validation, so 1 min before Flip Lottery.

First flip in long loaded
![image](https://user-images.githubusercontent.com/37978870/90331554-ad6e8f00-dfb5-11ea-832d-3dedf3eb1382.png)

Others failed
![image](https://user-images.githubusercontent.com/37978870/90331558-b52e3380-dfb5-11ea-8ee5-cc9cb1a61574.png)

Lost 1k stake and rewards... :(

**Comment by dragos9326** [comment]
Hi,

I faced the same problem this validation. I couldn't pass long because it was not loaded. I attach logs and print screen.

[log.zip](https://github.com/idena-network/idena-go/files/5145487/log.zip)
![image](https://user-images.githubusercontent.com/27893340/91640723-58f0f800-ea28-11ea-8819-1e4f2c92f132.png)

Me too lost 1k stake and rewards :(.

**Comment by ridenaio** [comment]
Hi, the issue is too old, please feel free to create a new one if the problem still exists.
