### ISSUE TITLE
Evidence map not broadcast if using web client

### ISSUE THREAD

**Issue by leocornelius** [idena-network/idena-go#712]
Hello! 
I've been reading through the code and through testing, I've found that a nodes evidence map will not be broadcast if they don't use the API method to submit answers but instead form a answers txn. This is not vital, however, it reduces the number of evidence maps that will be broadcast and hence increases the number of wrongly failed validations. 
This is caused by the line https://github.com/idena-network/idena-go/blob/38d7cb3305a58653545d0795401f7270132d475a/core/ceremony/ceremony.go#L745
In which the node checks if they have locally cached long answers, however, these long answer caches are only added if you use the SubmitLongAnswers API method: (
https://github.com/idena-network/idena-go/blob/master/api/flip_api.go#L406 
that then calls 
https://github.com/idena-network/idena-go/blob/38d7cb3305a58653545d0795401f7270132d475a/core/ceremony/ceremony.go#L266)

As the evidence map only regards short answers, it can be broadcast any time during the Long session, perhaps waiting a few seconds to ensure all txns have been processed. I'm looking to contribute to idena in some way so if it's ok with you guys I will open a PR implementing this.

Alternatively caching long answers to the DB when they are submitted as a raw txn too. 

Regards, Leo.

**Comment by midenaio** [comment]
Each node participating in validation listens to the network and collects the following messages: short answers proofs and flip keys sent by other participants during the short session. The node sends an evidence transaction to vote whether these messages are received in time from every challenged address. Then based on mined evidence txs the network decides whether these messages were properly broadcasted and received in time by the network majority. 

By design evidence transactions aren't sent when a user gets validation via the web client. The web client doesn't listen to the network during the validation so it can't vote. We also should not trust a shared node since this can be abused by its owner (especially when a significant number of users are connected to the shared node). 

Anyway thanks for reviewing the code !
